import { CellConfig } from "../store/game/game.types";
import { boardColor, teamAColor, teamBColor } from "./cellColors";

export const defaultCellsConfig: CellConfig[] = [
    {
        id: 0,
        color: teamAColor,
        animal: 'giraffe',
        teamName: 'blue',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 1,
        color: teamAColor,
        animal: 'lion',
        teamName: 'blue',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 2,
        color: teamAColor,
        animal: 'elephant',
        teamName: 'blue',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 3,
        color: boardColor,
        animal: '',
        teamName: '',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 4,
        color: teamAColor,
        animal: 'chicken',
        teamName: 'blue',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 5,
        color: boardColor,
        animal: '',
        teamName: '',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 6,
        color: boardColor,
        animal: '',
        teamName: '',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 7,
        color: teamBColor,
        animal: 'chicken',
        teamName: 'green',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 8,
        color: boardColor,
        animal: '',
        teamName: '',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 9,
        color: teamBColor,
        animal: 'elephant',
        teamName: 'green',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 10,
        color: teamBColor,
        animal: 'lion',
        teamName: 'green',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
    {
        id: 11,
        color: teamBColor,
        animal: 'giraffe',
        teamName: 'green',
        isClickable: false,
        isSelected: false,
        isAtRiskOfAttack: false,
    },
]
